[package]
name = "ppsc-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ppsc-core = { path = "../core" }
ppsc-crypto = { path = "../crypto" }

[dev-dependencies]
ark-bn254 = "0.4"
rand = "0.8"

[lints]
workspace = true

